const USER_TICKET_STATUS = {
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  SUCCESS: 'SUCCESS',
  EXPIRED: 'EXPIRED',
  CANCELED: 'CANCELED',
};

module.exports = {
  USER_TICKET_STATUS,
  USER_TICKET_STATUS_VALUES: Object.values(USER_TICKET_STATUS),
};
