const { SERVICE_OPTIONS } = require('./planningConstants');

const VENDOR_STATUS = {
  YET_TO_SELECT: 'YET_TO_SELECT',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
};

const VENDOR_STATUS_VALUES = Object.values(VENDOR_STATUS);

const VENDOR_SELECTION_STATUS = {
  MANAGER_YET_TO_BE_ASSIGNED: 'MANAGER_YET_TO_BE_ASSIGNED',
  IN_REVIEW: 'IN_REVIEW',
  FINALIZED: 'FINALIZED',
  COMPLETE: 'COMPLETE',
};

const VENDOR_SELECTION_STATUS_VALUES = Object.values(VENDOR_SELECTION_STATUS);

module.exports = {
  SERVICE_OPTIONS,
  VENDOR_STATUS,
  VENDOR_STATUS_VALUES,
  VENDOR_SELECTION_STATUS,
  VENDOR_SELECTION_STATUS_VALUES,
};
